name: Build and Deploy HTML

on:
  push:
    branches:
      - main  # Triggered whenever you push to the main branch

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install System Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Generate HTML
        run: |
          python scripts/estrutura.py
          python scripts/webapps.py
          python scripts/dio.py
          python generate_site.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # The folder where your generated HTML is located
          publish_branch: gh-pages  # The automated branch for the website